SET FOREIGN_KEY_CHECKS=0;
DELETE FROM ADMINISTRATION;
DELETE FROM BRAND;
DELETE FROM CAR;
DELETE FROM CAR_DETAILS;
DELETE FROM CAR_ORDER_DETAILS;
DELETE FROM CARORDER;
DELETE FROM CLIENT;
SET FOREIGN_KEY_CHECKS=1;

INSERT INTO ADMINISTRATION VALUES('Administration',1,'przemoemo@wp.pl','przemo','emo','przemek123','123123123');
INSERT INTO ADMINISTRATION VALUES('Employee',2,'jan@wp.pl','jan','ek','ek123','123123123');
INSERT INTO ADMINISTRATION VALUES('Supervisor',3,'super@wp.pl','super','visor','visor','687678678');

INSERT INTO CLIENT VALUES(1,'client@wp.pl','clie','nt','client','345345345');
INSERT INTO CLIENT VALUES(2,'client@wp.pl','clie','nt','client','345345345');


INSERT INTO BRAND VALUES(1,2,2,'BMW');
INSERT INTO BRAND VALUES(2,1,2,'AUDI');

INSERT INTO CAR VALUES(1,false,'997',2);
INSERT INTO CAR VALUES(2,true,'plate',2);
INSERT INTO CAR VALUES(3,true,'ad43',1);
INSERT INTO CAR VALUES(4,true,'cv33',1);

INSERT INTO CAR_DETAILS VALUES(1,'blue',2,2);
INSERT INTO CAR_DETAILS VALUES(2,'white',2,2);
INSERT INTO CAR_DETAILS VALUES(3,'yellow',2,2);
INSERT INTO CAR_DETAILS VALUES(4,'green',2,2);

INSERT INTO CARORDER VALUES(1,2,2);

INSERT INTO CAR_ORDER_DETAILS VALUES(1,'2011-03-12','2020-03-12',false,200,1);

UPDATE hibernate_sequence SET next_val=50;






